ldap_server: "ldap://192.168.X.X:389"
bind_dn: "cn=VOTRE_USER,dc=DOMAIN,dc=LOCAL"
password: "VOTRE_MOT_DE_PASSE"
base_dn: "dc=DOMAIN,dc=LOCAL"
use_ssl: false
smb_server: "192.168.X.X"
smb_username: "administrator"
smb_password: "VOTRE_MOT_DE_PASSE"
smb_domain: "DOMAIN"