name: Go

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest # On teste d'abord sur Linux pour valider
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Fix Dependencies
        run: |
          go mod tidy
          
      - name: Build
        # Cette commande cherche le main.go peu importe si le dossier est adgo ou ADgo
        run: go build -v -o adgo-binary ./cmd/adgo/main.go
